### ISSUE TITLE
Cannot read property 'screens' of undefined

### ISSUE THREAD

**Issue by yonaskolb** [CarlosBonetti/zacs#1]
Does this still work? I'm getting the following error
```
app_1  | 2019-02-22T04:07:51.940Z info: 		Listening on port 3000
app_1  | 2019-02-22T04:07:55.655Z info: 		Retrieving API data for project 5af8ec346b8f2c4322b0091a
app_1  | 2019-02-22T04:07:57.665Z error: 		Cannot read property 'screens' of undefined
```

**Comment by CarlosBonetti** [comment]
The message is not very informative but you're probably trying to request a project that does not exist or that is not public.

If it's a private project, you have to set the `ZEPLIN_USERNAME` and `ZEPLIN_PASSWORD` environment variables.

**Comment by CarlosBonetti** [comment]
Other possibility is your user does not have access to the project.

**Comment by CarlosBonetti** [comment]
Closed due to inactivity
